### ISSUE TITLE
Initial TODO

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/Scout-REViewer-service#3]
## TODO

- [x] get files from remote
- [x] store files on server
- [x] run REViewer with local file path as arguments
- [x] send back REViewer generated SVG
- [x] bundle REViewer
- [x] Dockerize
- ~make smaller docker build~
- [x] delete tmp files, maybe it's good if this also runs as some kind of chron job
- [x] tests
- [x] more tests – primarily for optional post values
- ~more tests 2 – check that it fails well with wrong input~
- ~unit tests - low prio~
- ~make sure to check if all files are created correctly after fetching~
- ~validate urls – add helpful error messages if wrong file input (check that a file is download)~
- ~prettify && DRY up~

- [x] API documentation
- [x] make it possible to select port through .env variables – docker

- ~handle files that are too large – test? low priority~
- ~security – should be enough for now since this will be an internal service~

- [x] add viewBox attribute to allow for responsive scaling when added to HTML
